version: "3.9"

services:
#  db:
#    image: postgres:latest
#    container_name: db
#    volumes:
#      - "~/.pg/pg_data/project:/var/lib/postgresql/data"
#    env_file:
#      - .env
  web:
    image: project:1.0
    container_name: web
#    depends_on:
#      - db
    volumes:
      - static_volume:/project/public/static
      - media_volume:/project/public/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 project.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: project_nginx
    image: project_nginx
    volumes:
      - static_volume:/project/public/static
      - media_volume:/project/public/media
    depends_on:
      - web
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
